// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebOrigoTask.Data;

#nullable disable

namespace WebOrigoTask.Data.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220825125942_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("WebOrigoTask.Data.device", b =>
                {
                    b.Property<int>("device_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("accept")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("activation_code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("appversion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("device_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("device_id");

                    b.ToTable("Tablets");

                    b.HasData(
                        new
                        {
                            device_id = 1,
                            accept = "",
                            activation_code = "XJ235IAH245D2O",
                            appversion = "",
                            device_type = "unset"
                        },
                        new
                        {
                            device_id = 2,
                            accept = "",
                            activation_code = "XJ235IAH245D2O",
                            appversion = "",
                            device_type = "unset"
                        },
                        new
                        {
                            device_id = 3,
                            accept = "",
                            activation_code = "XJ235IAH245D2O",
                            appversion = "",
                            device_type = "unset"
                        },
                        new
                        {
                            device_id = 4,
                            accept = "",
                            activation_code = "XJ235IAH245D2O",
                            appversion = "",
                            device_type = "unset"
                        },
                        new
                        {
                            device_id = 5,
                            accept = "",
                            activation_code = "XJ235IAH245D2O",
                            appversion = "",
                            device_type = "unset"
                        },
                        new
                        {
                            device_id = 6,
                            accept = "",
                            activation_code = "XJ235IAH245D2O",
                            appversion = "",
                            device_type = "unset"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
