// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebOrigoTask.Data;

#nullable disable

namespace WebOrigoTask.Data.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220825150910_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("WebOrigoTask.Data.device", b =>
                {
                    b.Property<string>("deviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("accept")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("activationCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("appVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("deviceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("deviceId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            deviceId = "NW-H-20-0017",
                            accept = "",
                            activationCode = "XJ235IAH245D2O",
                            appVersion = "",
                            deviceType = "unset"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
